// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tdbskqkbkybwxuzbkeoq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYnNrcWtia3lid3h1emJrZW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3NDM0ODcsImV4cCI6MjA0ODMxOTQ4N30.AkgILDB5ya0h_PrnfyxtL-zf-6YzXKiafoVLZwP-4o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);